apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: retain
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud